
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.16.27054 для x64
      (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.16.27054.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        D:/cliionproject/skillbox_notGIT/38_3_blur/build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug/CMakeFiles/4.0.0-rc1/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1281 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Примечание: включение файла:  d:\\cliionproject\\skillbox_notgit\\38_3_blur\\build-blur-desktop_qt_5_12_12_msvc2017_64bit-debug\\cmakefiles\\showincludes\\foo.h
        
      Found prefix "Примечание: включение файла:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:81 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/cliionproject/skillbox_notGIT/38_3_blur/build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug/CMakeFiles/CMakeScratch/TryCompile-90385c"
      binary: "D:/cliionproject/skillbox_notGIT/38_3_blur/build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug/CMakeFiles/CMakeScratch/TryCompile-90385c"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/cliionproject/skillbox_notGIT/38_3_blur/build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug/CMakeFiles/CMakeScratch/TryCompile-90385c'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 jom -f Makefile /nologo cmTC_5f8de\\fast
        jom: parallel job execution disabled for Makefile
        	D:\\Qt\\Tools\\QtCreator\\bin\\jom\\jom.exe  -f CMakeFiles\\cmTC_5f8de.dir\\build.make /nologo -L CMakeFiles\\cmTC_5f8de.dir\\build
        Building CXX object CMakeFiles/cmTC_5f8de.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_5f8de.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=D:\\cliionproject\\skillbox_notGIT\\38_3_blur\\build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-90385c --filter-prefix="╤?е?╤ў╤м╤це?╤°╤л╤ў╤ц: ╤¤╤з╤пе?е?╤ц╤л╤ў╤ц е?╤°╤√╤п╤°:  " -- C:\\PROGRA~2\\MICROS~2\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1416~1.270\\bin\\HostX64\\x64\\cl.exe @C:\\Users\\ilyap\\AppData\\Local\\Temp\\CMakeCXXCompilerABI.cpp.obj.27704.15.jom
        CMakeCXXCompilerABI.cpp
        ╨Я╤А╨╕╨╝╨╡╤З╨░╨╜╨╕╨╡: ╨▓╨║╨╗╤О╤З╨╡╨╜╨╕╨╡ ╤Д╨░╨╣╨╗╨░:  c:\\program files\\cmake\\share\\cmake-4.0\\modules\\CMakeCompilerABI.h
        Linking CXX executable cmTC_5f8de.exe
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E vs_link_exe --msvc-ver=1916 --intdir=CMakeFiles\\cmTC_5f8de.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~2\\MICROS~2\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1416~1.270\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_5f8de.dir\\objects1.rsp @C:\\Users\\ilyap\\AppData\\Local\\Temp\\cmTC_5f8de.exe.27704.359.jom
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_5f8de.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_5f8de.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_5f8de.dir/manifest.res CMakeFiles\\cmTC_5f8de.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~2\\MICROS~2\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1416~1.270\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_5f8de.dir\\objects1.rsp /out:cmTC_5f8de.exe /implib:cmTC_5f8de.lib /pdb:D:\\cliionproject\\skillbox_notGIT\\38_3_blur\\build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-90385c\\cmTC_5f8de.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_5f8de.dir/intermediate.manifest CMakeFiles\\cmTC_5f8de.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_5f8de.dir/intermediate.manifest /out:CMakeFiles\\cmTC_5f8de.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_5f8de.dir/manifest.res CMakeFiles\\cmTC_5f8de.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~2\\MICROS~2\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1416~1.270\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_5f8de.dir\\objects1.rsp /out:cmTC_5f8de.exe /implib:cmTC_5f8de.lib /pdb:D:\\cliionproject\\skillbox_notGIT\\38_3_blur\\build-blur-Desktop_Qt_5_12_12_MSVC2017_64bit-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-90385c\\cmTC_5f8de.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_5f8de.dir/intermediate.manifest CMakeFiles\\cmTC_5f8de.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:225 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/PROGRA~2/MICROS~2/2017/COMMUN~1/VC/Tools/MSVC/1416~1.270/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:262 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Running the CXX compiler's linker: "C:/PROGRA~2/MICROS~2/2017/COMMUN~1/VC/Tools/MSVC/1416~1.270/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.16.27054.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
